version: '3.3'

services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  knight-todo:
    restart: always
    build: .
    ports:
      - "6080:6080"
  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:10.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak_db
    ports:
      - '5433:5432'
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: adm
      KEYCLOAK_PASSWORD: adm
    ports:
      - "8484:8080"
    depends_on:
      - postgres-keycloak
    links:
      - "postgres-keycloak:postgres-keycloak"
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
