version: '3.3'

services:
  postgres:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_DB=knight
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  knight-todo:
    build: .
    ports:
      - "127.0.0.1:6080:6031"
