server:
  port: 6031
  servlet:
    context-path: /api

logging:
  level:
    com.knighttodo.knighttodo: DEBUG

spring:
  output:
    ansi:
      enabled: NEVER
  #Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/knight?currentSchema=knight_todo
    username: postgre
    password: postgre
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          #          issuer-uri: http://localhost:8080/auth/realms/development
          jwk-set-uri: http://localhost:8080/auth/realms/development/protocol/openid-connect/certs

baseUrl:
  experience: "http://localhost:6070"
