server:
  port: 6031

logging:
  level:
    com.knighttodo.knighttodo: INFO

spring:
  output:
    ansi:
      enabled: NEVER
  datasource:
    url: jdbc:postgresql://localhost:5432/knight?currentSchema=knight_todo
    username: postgre
    password: postgre
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

baseUrl:
  experience: "http://localhost:6070"
