server:
  port: 6031
  servlet:
    context-path: /api

logging:
  level:
    com.knighttodo.knighttodo: INFO

spring:
  output:
    ansi:
      enabled: NEVER

baseUrl:
  experience: "http://localhost:6070"
