### create day
POST localhost:8080/api/v1/days
Content-Type: application/json

< json/day/createDay.json

### update day
PUT {{host}}/days/{{dayId}}
Content-Type: application/json

< json/day/updateDay.json

### get all days
GET {{host}}/days

### get day by id
GET {{host}}/days/{{dayId}}

### delete day by id
DELETE {{host}}/days/{{dayId}}

### find day by date
GET localhost:8080/api/v1/days/date?date=2023-02-14
