server:
  port: 8080

spring:
  profiles:
    include: todoapp, character

  todocore:
    datasource:
      driverClassName: org.postgresql.Driver
      username: postgre
      password: postgre
      platform: postgres
      jdbcUrl: jdbc:postgresql://localhost:5432/knight?currentSchema=knight_todo
  character:
    datasource:
      driverClassName: org.postgresql.Driver
      username: postgre
      password: postgre
      platform: postgres
      jdbcUrl: jdbc:postgresql://localhost:5432/knight?currentSchema=knight_character
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      enabled: true
    liquibase:
      enabled: true
    loggers:
      enabled: true
    web:
      exposure:
        include: '*'
